[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
sdl2 = { version = "0.35.2", features = ["image", "ttf"] }

rand = "0.8.4"